name: Release
run-name: 🚀 Release - ${{ github.actor }}
on:
  push:
    branches: [ main ] # TODO - change to 'release' when done testing
  workflow_dispatch: # allow manual triggering

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yaml
    secrets:
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_KEY: ${{ secrets.EC2_KEY }}
      RDS_DATASOURCE_URL: ${{ secrets.RDS_DATASOURCE_URL }}
      RDS_DATASOURCE_USERNAME: ${{ secrets.RDS_DATASOURCE_USERNAME }}
      RDS_DATASOURCE_PASSWORD: ${{ secrets.RDS_DATASOURCE_PASSWORD }}